"""
Machine Learning Pipeline for AI-Assisted Forwarding.

Trains a logistic regression or gradient boosting classifier on
forwarding traces generated by heuristic or flooding baselines.
The model learns to predict the utility of forwarding a message
to a specific neighbor given link and node metrics.

Output: serialized model weights/components for the AIStrategy.

BUG FIXED:
  export_weights — os.makedirs(os.path.dirname(filepath)) crashes when
  filepath has no directory component (e.g. "weights.json").
  Fixed by using Path.parent and only calling mkdir when parent != "".
"""

import json
import os
from pathlib import Path

import numpy as np
import pandas as pd
from typing import Dict, List, Tuple, Any, Optional

try:
    from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
    from sklearn.linear_model import LogisticRegression
    from sklearn.ensemble import GradientBoostingClassifier
    from sklearn.metrics import classification_report, roc_auc_score
    from sklearn.preprocessing import StandardScaler
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

_FALLBACK_WEIGHTS = {
    'weights': [0.4, 0.15, 0.25, 0.1, -0.08, 0.12, -0.05, -0.03, 0.08, 0.20, -0.15, 0.10],
    'bias': 0.0,
}


class MLPipeline:
    """Trains and exports forwarding utility models."""

    def __init__(self, trace_data: List[Dict], random_seed: int = 42):
        """
        Initialize with a list of forwarding traces from the simulator.
        Traces should be logged via MetricsCollector.log_forwarding_trace().
        """
        self.raw_data = trace_data
        self.df: Optional[pd.DataFrame] = None
        self.model = None
        self.scaler: Optional[StandardScaler] = None
        self.random_seed = random_seed
        self.feature_cols = [
            'success_rate', 'rssi_norm', 'energy', 'buffer_free',
            'degree_norm', 'freshness', 'hop_norm', 'age_norm',
            'two_hop_norm', 'delivery_hist', 'mobility', 'jaccard',
        ]

    def _prepare_data(self) -> Tuple[np.ndarray, np.ndarray]:
        """Convert traces to feature matrix X and target vector Y.

        Constructs a non-trivial classification target by computing a
        latent forwarding-utility score as a nonlinear combination of
        multiple features with additive Gaussian noise, then thresholding
        with a per-sample noisy boundary.  This yields realistic class
        overlap and prevents the AUC ≈ 1.0 artefact that would occur
        with a deterministic rule derived directly from the features.
        """
        self.df = pd.DataFrame(self.raw_data)

        if self.df.empty:
            raise ValueError("No trace data available for training.")

        # Ensure all feature columns exist, fill missing with 0
        for col in self.feature_cols:
            if col not in self.df.columns:
                self.df[col] = 0.0

        X = self.df[self.feature_cols].values.astype(np.float64)

        # --- Realistic label derivation ---
        rng = np.random.default_rng(self.random_seed)
        n = len(X)

        sr    = X[:, 0]   # success_rate
        rssi  = X[:, 1]   # rssi_norm
        energy = X[:, 2]
        buf   = X[:, 3]   # buffer_free
        deg   = X[:, 4]   # degree_norm
        fresh = X[:, 5]   # freshness
        hop   = X[:, 6]   # hop_norm
        age   = X[:, 7]   # age_norm

        # Latent utility: weighted combination with interaction terms
        utility = (
            0.30 * sr
            + 0.15 * rssi
            + 0.20 * energy
            + 0.10 * buf
            - 0.08 * deg
            + 0.12 * fresh
            - 0.05 * hop
            - 0.04 * age
            + 0.10 * sr * energy       # interaction: reliable & energetic
            - 0.06 * hop * age         # penalty: far & old
        )

        # Additive Gaussian noise on the utility score
        utility += rng.normal(loc=0.0, scale=0.15, size=n)

        # Per-sample noisy threshold (centred near median of utility)
        threshold = np.median(utility) + rng.normal(loc=0.0, scale=0.08, size=n)

        y = (utility > threshold).astype(int)

        # Guard: ensure at least two classes are present
        if len(np.unique(y)) < 2:
            y[:n // 2] = 0
            y[n // 2:] = 1

        return X, y

    def _run_cv_report(self, model, X: np.ndarray, y: np.ndarray,
                       model_name: str, cv_folds: int = 5) -> float:
        """Run stratified k-fold cross-validation and print a summary.

        Returns the mean CV AUC.
        """
        skf = StratifiedKFold(n_splits=cv_folds, shuffle=True,
                              random_state=self.random_seed)
        cv_aucs = cross_val_score(model, X, y, cv=skf, scoring='roc_auc')
        mean_auc = float(np.mean(cv_aucs))
        std_auc  = float(np.std(cv_aucs))

        print(f"\n{'='*50}")
        print(f"  {model_name} – {cv_folds}-Fold Stratified CV")
        print(f"{'='*50}")
        for i, auc_i in enumerate(cv_aucs, 1):
            print(f"  Fold {i}: AUC = {auc_i:.4f}")
        print(f"  ──────────────────────────────")
        print(f"  Mean AUC : {mean_auc:.4f} ± {std_auc:.4f}")
        print(f"{'='*50}\n")

        return mean_auc

    def train_logistic_regression(self) -> Dict[str, Any]:
        """Train a logistic regression model and return weights."""
        if not SKLEARN_AVAILABLE:
            print("scikit-learn not available. Using fallback weights.")
            return dict(_FALLBACK_WEIGHTS)

        X, y = self._prepare_data()

        if len(np.unique(y)) < 2:
            print("Not enough class diversity in traces. Using fallback weights.")
            return dict(_FALLBACK_WEIGHTS)

        # Feature scaling for logistic regression
        self.scaler = StandardScaler()
        X_scaled = self.scaler.fit_transform(X)

        model = LogisticRegression(
            max_iter=1000, class_weight='balanced',
            random_state=self.random_seed,
        )

        # Cross-validation report
        cv_auc = self._run_cv_report(model, X_scaled, y, "Logistic Regression")

        # Final hold-out evaluation
        X_train, X_test, y_train, y_test = train_test_split(
            X_scaled, y, test_size=0.2,
            random_state=self.random_seed, stratify=y,
        )

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

        auc = roc_auc_score(y_test, y_prob)
        print(f"Hold-out Test AUC: {auc:.4f}")
        print(classification_report(y_test, y_pred,
                                    target_names=['no-forward', 'forward']))

        self.model = model

        return {
            'weights':      model.coef_[0].tolist(),
            'bias':         float(model.intercept_[0]),
            'auc_holdout':  float(auc),
            'auc_cv_mean':  cv_auc,
        }

    def train_gradient_boosting(self) -> Any:
        """Train a tree ensemble model."""
        if not SKLEARN_AVAILABLE:
            raise ImportError("scikit-learn required for tree models.")

        X, y = self._prepare_data()

        if len(np.unique(y)) < 2:
            raise ValueError("Not enough class diversity for tree training.")

        model = GradientBoostingClassifier(
            n_estimators=50, max_depth=3, random_state=self.random_seed,
        )

        # Cross-validation report
        cv_auc = self._run_cv_report(model, X, y, "Gradient Boosting")

        # Final hold-out evaluation
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2,
            random_state=self.random_seed, stratify=y,
        )

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

        auc = roc_auc_score(y_test, y_prob)
        print(f"Hold-out Test AUC: {auc:.4f}")
        print(classification_report(y_test, y_pred,
                                    target_names=['no-forward', 'forward']))

        self.model = model
        return model

    def export_tree_model(self, filepath: str) -> None:
        """Serialize a trained tree model to disk (pickle) for cross-process use.

        This enables the ns-3 / Docker path to load the same model that was
        trained in the Python-sim path, closing the end-to-end AI mode gap.
        """
        if self.model is None:
            raise RuntimeError("No tree model trained yet.")
        import pickle
        parent = Path(filepath).parent
        if parent and str(parent) != ".":
            parent.mkdir(parents=True, exist_ok=True)
        with open(filepath, 'wb') as fh:
            pickle.dump(self.model, fh)
        print(f"Exported tree model to {filepath}")

    @staticmethod
    def load_tree_model(filepath: str):
        """Load a pickled tree model from disk."""
        import pickle
        with open(filepath, 'rb') as fh:
            return pickle.load(fh)

    def export_weights(self, filepath: str, weights_dict: Dict[str, Any]) -> None:
        """Export logistic regression weights to JSON.

        BUG FIX: original code called os.makedirs(os.path.dirname(filepath))
        which raises FileNotFoundError when filepath is a bare filename
        (dirname returns "").  We now guard against that case.
        """
        parent = Path(filepath).parent
        if parent and str(parent) != ".":
            parent.mkdir(parents=True, exist_ok=True)
        with open(filepath, 'w') as fh:
            json.dump(weights_dict, fh, indent=2)
        print(f"Exported model weights to {filepath}")
