"""
Metrics Collection and Computation for CRDT Mesh Network Simulation.

Provides comprehensive instrumentation for capturing, storing, and
computing all performance metrics required for IEEE publication:

Primary Metrics:
    - Packet Delivery Ratio (PDR)
    - End-to-End Latency (mean, median, P95, std)
    - Convergence Time (time to global consistency)
    - Control Overhead (ratio of control to data bytes)
    - Duplicate Ratio (redundant receptions)
    - Energy Consumption (total and per-node)
    - Recovery Ratio (post-partition consistency restoration)
    - Buffer Occupancy (memory utilization)

Secondary Metrics:
    - Forwarding Efficiency (unique deliveries per transmission)
    - Link Utilization (fraction of link capacity used)
    - Fairness Index (Jain's fairness across nodes)
    - Network Lifetime (time until first/10% node death)
"""

from __future__ import annotations

import csv
import io
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional, Set, Tuple

import numpy as np


class EventType(Enum):
    """Types of events logged by the metrics collector."""
    MSG_CREATED = auto()        # Message generated by a node
    MSG_SENT = auto()           # Message transmitted over the air
    MSG_RECEIVED = auto()       # Message successfully received
    MSG_DELIVERED = auto()      # Message reaches a new node (unique reception)
    MSG_FORWARDED = auto()      # Message forwarded by relay node
    MSG_DUPLICATE = auto()      # Duplicate message detected and dropped
    MSG_DROPPED_BUFFER = auto() # Message dropped due to full buffer
    MSG_DROPPED_TTL = auto()    # Message dropped due to TTL expiry
    MSG_DROPPED_ENERGY = auto() # Message dropped due to insufficient energy
    MSG_DROPPED_CHANNEL = auto()# Message lost during transmission

    SYNC_HELLO = auto()         # HELLO beacon sent
    SYNC_SUMMARY = auto()       # State summary exchanged
    SYNC_REQUEST = auto()       # Delta request sent
    SYNC_DELTA = auto()         # Delta response sent
    SYNC_MERGE = auto()         # CRDT merge performed

    NODE_START = auto()         # Node activated
    NODE_FAILURE = auto()       # Node crashed
    NODE_RECOVERY = auto()      # Node recovered from crash
    NODE_ENERGY_DEPLETED = auto()  # Node ran out of energy

    PARTITION_START = auto()    # Network partition begins
    PARTITION_END = auto()      # Network partition heals

    CONVERGENCE_CHECK = auto()  # Periodic convergence verification


@dataclass
class LogEntry:
    """Single event log record."""
    time: float
    node_id: int
    event_type: EventType
    msg_origin: int = -1
    msg_seq: int = -1
    details: Dict[str, Any] = field(default_factory=dict)


class MetricsCollector:
    """
    Comprehensive metrics collection and computation engine.

    Logs all simulation events and provides methods to compute
    publication-quality statistics with confidence intervals.
    """

    def __init__(self, n_nodes: int):
        self.n_nodes = n_nodes
        self.log: List[LogEntry] = []

        # Fast lookup indices
        self._msg_created: Dict[Tuple[int, int], float] = {}  # (origin, seq) → time
        self._msg_creator: Dict[Tuple[int, int], int] = {}    # (origin, seq) → node_id
        self._msg_deliveries: Dict[Tuple[int, int], Dict[int, float]] = defaultdict(dict)
        self._msg_duplicates: Dict[Tuple[int, int], int] = defaultdict(int)

        # Per-node counters
        self._node_sent: Dict[int, int] = defaultdict(int)
        self._node_received: Dict[int, int] = defaultdict(int)
        self._node_forwarded: Dict[int, int] = defaultdict(int)
        self._node_duplicates: Dict[int, int] = defaultdict(int)
        self._node_dropped: Dict[int, int] = defaultdict(int)

        # Energy tracking
        self._node_energy_consumed: Dict[int, float] = defaultdict(float)
        self._node_energy_initial: Dict[int, float] = {}

        # Byte counters
        self._data_bytes_sent: int = 0
        self._control_bytes_sent: int = 0
        self._duplicate_bytes: int = 0

        # Partition tracking
        self._partition_periods: List[Tuple[float, float]] = []
        self._partition_start: Optional[float] = None

        # Convergence tracking
        self._convergence_times: List[float] = []

        # Forwarding trace for ML training
        self.forwarding_traces: List[Dict] = []

    def log_event(
        self,
        time: float,
        node_id: int,
        event_type: EventType,
        msg_origin: int = -1,
        msg_seq: int = -1,
        **details,
    ):
        """Record a simulation event."""
        entry = LogEntry(
            time=time,
            node_id=node_id,
            event_type=event_type,
            msg_origin=msg_origin,
            msg_seq=msg_seq,
            details=details,
        )
        self.log.append(entry)

        msg_key = (msg_origin, msg_seq)

        # Update fast indices
        if event_type == EventType.MSG_CREATED:
            self._msg_created[msg_key] = time
            self._msg_creator[msg_key] = node_id
            self._node_sent[node_id] += 1

        elif event_type == EventType.MSG_DELIVERED:
            self._msg_deliveries[msg_key][node_id] = time
            self._node_received[node_id] += 1
            size = details.get('size_bytes', 64)
            self._data_bytes_sent += size

        elif event_type == EventType.MSG_FORWARDED:
            self._node_forwarded[node_id] += 1

        elif event_type == EventType.MSG_DUPLICATE:
            self._msg_duplicates[msg_key] += 1
            self._node_duplicates[node_id] += 1
            size = details.get('size_bytes', 64)
            self._duplicate_bytes += size

        elif event_type in (EventType.MSG_DROPPED_BUFFER,
                            EventType.MSG_DROPPED_TTL,
                            EventType.MSG_DROPPED_ENERGY,
                            EventType.MSG_DROPPED_CHANNEL):
            self._node_dropped[node_id] += 1

        elif event_type == EventType.MSG_SENT:
            size = details.get('size_bytes', 64)
            self._data_bytes_sent += size

        elif event_type in (EventType.SYNC_HELLO, EventType.SYNC_SUMMARY,
                            EventType.SYNC_REQUEST, EventType.SYNC_DELTA):
            size = details.get('size_bytes', 32)
            self._control_bytes_sent += size

        elif event_type == EventType.PARTITION_START:
            self._partition_start = time

        elif event_type == EventType.PARTITION_END:
            if self._partition_start is not None:
                self._partition_periods.append((self._partition_start, time))
                self._partition_start = None

    def log_energy(self, node_id: int, consumed: float, initial: float = None):
        """Record energy consumption for a node."""
        self._node_energy_consumed[node_id] += consumed
        if initial is not None and node_id not in self._node_energy_initial:
            self._node_energy_initial[node_id] = initial

    def log_forwarding_trace(self, trace: Dict):
        """Record a forwarding decision for ML training data."""
        self.forwarding_traces.append(trace)

    # ─────────────────────────────────────────────────────────────
    # PRIMARY METRICS
    # ─────────────────────────────────────────────────────────────

    def compute_pdr(self) -> float:
        """
        Packet Delivery Ratio.

        PDR = (unique messages received by at least one non-origin node)
              / (total messages created)

        For per-message granularity:
        PDR_global = Σ_m (nodes_that_received_m / (N-1)) / total_messages
        """
        if not self._msg_created:
            return 0.0

        total_possible = 0
        total_delivered = 0

        for msg_key, create_time in self._msg_created.items():
            creator = self._msg_creator.get(msg_key, -1)
            deliveries = self._msg_deliveries.get(msg_key, {})

            # Count unique nodes that received this message (excluding creator)
            recipients = {nid for nid in deliveries.keys() if nid != creator}
            possible = self.n_nodes - 1  # all nodes except creator

            total_delivered += len(recipients)
            total_possible += possible

        if total_possible == 0:
            return 0.0
        return total_delivered / total_possible

    def compute_pdr_per_message(self) -> List[float]:
        """PDR for each individual message."""
        pdrs = []
        for msg_key in self._msg_created:
            creator = self._msg_creator.get(msg_key, -1)
            deliveries = self._msg_deliveries.get(msg_key, {})
            recipients = {nid for nid in deliveries.keys() if nid != creator}
            possible = self.n_nodes - 1
            if possible > 0:
                pdrs.append(len(recipients) / possible)
        return pdrs

    def compute_latency(self) -> Dict[str, float]:
        """
        End-to-End Latency statistics.

        Latency = t_receive - t_create for each (message, receiver) pair.
        """
        latencies = []

        for msg_key, create_time in self._msg_created.items():
            creator = self._msg_creator.get(msg_key, -1)
            deliveries = self._msg_deliveries.get(msg_key, {})

            for node_id, recv_time in deliveries.items():
                if node_id != creator:
                    lat = recv_time - create_time
                    if lat >= 0:
                        latencies.append(lat)

        if not latencies:
            return {'mean': 0, 'median': 0, 'p95': 0, 'p99': 0,
                    'min': 0, 'max': 0, 'std': 0, 'count': 0}

        arr = np.array(latencies)
        return {
            'mean': float(np.mean(arr)),
            'median': float(np.median(arr)),
            'p95': float(np.percentile(arr, 95)),
            'p99': float(np.percentile(arr, 99)),
            'min': float(np.min(arr)),
            'max': float(np.max(arr)),
            'std': float(np.std(arr)),
            'count': len(latencies),
        }

    def compute_convergence_time(self) -> Dict[str, float]:
        """
        Convergence Time — time from message creation until all
        reachable nodes have received it.

        For each message m:
            conv_time(m) = max_i(t_receive(m, i)) - t_create(m)
        """
        conv_times = []

        for msg_key, create_time in self._msg_created.items():
            creator = self._msg_creator.get(msg_key, -1)
            deliveries = self._msg_deliveries.get(msg_key, {})
            recipients = {nid: t for nid, t in deliveries.items() if nid != creator}

            if recipients:
                last_delivery = max(recipients.values())
                conv_time = last_delivery - create_time
                if conv_time >= 0:
                    conv_times.append(conv_time)

        if not conv_times:
            return {'mean': 0, 'median': 0, 'max': 0, 'std': 0, 'count': 0}

        arr = np.array(conv_times)
        return {
            'mean': float(np.mean(arr)),
            'median': float(np.median(arr)),
            'max': float(np.max(arr)),
            'std': float(np.std(arr)),
            'count': len(conv_times),
        }

    def compute_overhead(self) -> Dict[str, float]:
        """
        Control overhead and duplicate overhead ratios.

        Control Overhead = control_bytes / data_bytes
        Duplicate Overhead = duplicate_bytes / data_bytes
        Total Overhead = (control + duplicate) / data
        """
        data = max(1, self._data_bytes_sent)
        return {
            'control_overhead': self._control_bytes_sent / data,
            'duplicate_overhead': self._duplicate_bytes / data,
            'total_overhead': (self._control_bytes_sent + self._duplicate_bytes) / data,
            'control_bytes': self._control_bytes_sent,
            'data_bytes': self._data_bytes_sent,
            'duplicate_bytes': self._duplicate_bytes,
        }

    def compute_duplicate_ratio(self) -> float:
        """
        Duplicate Ratio = total duplicate receptions / total receptions.
        """
        total_dups = sum(self._msg_duplicates.values())
        total_deliveries = sum(len(d) for d in self._msg_deliveries.values())
        total = total_dups + total_deliveries
        if total == 0:
            return 0.0
        return total_dups / total

    def compute_energy(self) -> Dict[str, float]:
        """
        Energy consumption statistics across all nodes.
        """
        if not self._node_energy_consumed:
            return {'mean': 0, 'total': 0, 'max': 0, 'min': 0, 'std': 0}

        values = list(self._node_energy_consumed.values())
        arr = np.array(values)

        return {
            'mean': float(np.mean(arr)),
            'total': float(np.sum(arr)),
            'max': float(np.max(arr)),
            'min': float(np.min(arr)),
            'std': float(np.std(arr)),
            'per_node': dict(self._node_energy_consumed),
        }

    def compute_recovery_ratio(self) -> Dict[str, float]:
        """
        Recovery Ratio after network partitions.

        Measures the fraction of messages generated during partition
        periods that were eventually delivered after reconnection.
        """
        if not self._partition_periods:
            return {'ratio': 1.0, 'total_msgs': 0, 'recovered_msgs': 0,
                    'avg_recovery_time': 0.0}

        partition_msgs = 0
        recovered_msgs = 0
        recovery_times = []

        for p_start, p_end in self._partition_periods:
            for msg_key, create_time in self._msg_created.items():
                # Message created during partition
                if p_start <= create_time <= p_end:
                    partition_msgs += 1
                    deliveries = self._msg_deliveries.get(msg_key, {})
                    creator = self._msg_creator.get(msg_key, -1)

                    # Check if it was delivered after partition ended
                    for nid, recv_time in deliveries.items():
                        if nid != creator and recv_time > p_end:
                            recovered_msgs += 1
                            recovery_times.append(recv_time - p_end)
                            break

        ratio = recovered_msgs / max(1, partition_msgs)
        avg_recovery = float(np.mean(recovery_times)) if recovery_times else 0.0

        return {
            'ratio': ratio,
            'total_msgs': partition_msgs,
            'recovered_msgs': recovered_msgs,
            'avg_recovery_time': avg_recovery,
        }

    # ─────────────────────────────────────────────────────────────
    # SECONDARY METRICS
    # ─────────────────────────────────────────────────────────────

    def compute_forwarding_efficiency(self) -> float:
        """
        Forwarding Efficiency = unique deliveries / total transmissions.
        """
        total_fwd = sum(self._node_forwarded.values()) + sum(self._node_sent.values())
        total_delivered = sum(len(d) for d in self._msg_deliveries.values())

        if total_fwd == 0:
            return 0.0
        return total_delivered / total_fwd

    def compute_fairness_index(self) -> float:
        """
        Jain's Fairness Index across node delivery counts.

        J = (Σ xᵢ)² / (n · Σ xᵢ²)

        J = 1.0 means perfect fairness.
        """
        counts = [self._node_received.get(i, 0) for i in range(self.n_nodes)]
        if not counts or max(counts) == 0:
            return 1.0

        arr = np.array(counts, dtype=float)
        numerator = np.sum(arr) ** 2
        denominator = len(arr) * np.sum(arr ** 2)

        if denominator == 0:
            return 1.0
        return float(numerator / denominator)

    def compute_buffer_occupancy(self, node_buffer_sizes: Dict[int, int],
                                  max_buffer: int = 256) -> Dict[str, float]:
        """Compute buffer occupancy statistics."""
        if not node_buffer_sizes:
            return {'mean': 0, 'max': 0, 'min': 0}

        occupancies = [s / max_buffer for s in node_buffer_sizes.values()]
        arr = np.array(occupancies)
        return {
            'mean': float(np.mean(arr)),
            'max': float(np.max(arr)),
            'min': float(np.min(arr)),
        }

    # ─────────────────────────────────────────────────────────────
    # SUMMARY & EXPORT
    # ─────────────────────────────────────────────────────────────

    def summary(self) -> Dict[str, Any]:
        """Compute all metrics and return as a dictionary."""
        return {
            'pdr': self.compute_pdr(),
            'latency': self.compute_latency(),
            'convergence': self.compute_convergence_time(),
            'overhead': self.compute_overhead(),
            'duplicate_ratio': self.compute_duplicate_ratio(),
            'energy': self.compute_energy(),
            'recovery': self.compute_recovery_ratio(),
            'forwarding_efficiency': self.compute_forwarding_efficiency(),
            'fairness': self.compute_fairness_index(),
            'total_messages_created': len(self._msg_created),
            'total_events_logged': len(self.log),
        }

    def flat_summary(self) -> Dict[str, float]:
        """Return a flat dictionary of scalar metrics for CSV export."""
        s = self.summary()
        flat = {
            'pdr': s['pdr'],
            'latency_mean': s['latency']['mean'],
            'latency_median': s['latency']['median'],
            'latency_p95': s['latency']['p95'],
            'latency_std': s['latency']['std'],
            'convergence_mean': s['convergence']['mean'],
            'convergence_max': s['convergence']['max'],
            'control_overhead': s['overhead']['control_overhead'],
            'duplicate_overhead': s['overhead']['duplicate_overhead'],
            'total_overhead': s['overhead']['total_overhead'],
            'duplicate_ratio': s['duplicate_ratio'],
            'energy_mean': s['energy']['mean'],
            'energy_total': s['energy']['total'],
            'recovery_ratio': s['recovery']['ratio'],
            'recovery_time': s['recovery']['avg_recovery_time'],
            'forwarding_efficiency': s['forwarding_efficiency'],
            'fairness': s['fairness'],
            'total_messages': s['total_messages_created'],
        }
        return flat

    def to_csv(self, filepath: Optional[str] = None) -> str:
        """Export event log as CSV string or file."""
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow([
            'time', 'node_id', 'event_type',
            'msg_origin', 'msg_seq', 'details'
        ])

        for entry in self.log:
            writer.writerow([
                f"{entry.time:.6f}",
                entry.node_id,
                entry.event_type.name,
                entry.msg_origin,
                entry.msg_seq,
                str(entry.details),
            ])

        csv_str = output.getvalue()

        if filepath:
            with open(filepath, 'w', newline='') as f:
                f.write(csv_str)

        return csv_str

    def get_forwarding_traces_df(self):
        """Return forwarding traces as a pandas DataFrame."""
        import pandas as pd
        return pd.DataFrame(self.forwarding_traces)

    def __repr__(self) -> str:
        return (
            f"MetricsCollector(events={len(self.log)}, "
            f"messages={len(self._msg_created)}, "
            f"nodes={self.n_nodes})"
        )
